zuul:
  prefix: /api-gateway
  routes:
    buyer:
      path: /buyer/**
      url: http://localhost:8082
    seller:
      path: /seller/**
      url: http://localhost:8087
    order-service:
      path: /order/**
      url: http://localhost:8084
    product-service:
      path: /crop/**
      url: http://localhost:8086
    transport-service:
      path: /vehicle/**
      url: http://localhost:8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
